import fs from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import {
  Connection,
  Keypair,
  NONCE_ACCOUNT_LENGTH,
  PublicKey,
  sendAndConfirmTransaction,
  SystemProgram,
  Transaction,
} from "@solana/web3.js";

function loadKeypair(secretKeyVariable: string, keypairPathVariable: string): Keypair | undefined {
  const secret = process.env[secretKeyVariable];
  if (secret !== undefined && secret.trim() !== "") {
    return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(secret)));
  }

  const path = process.env[keypairPathVariable];
  if (path !== undefined && path.trim() !== "") {
    return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(fs.readFileSync(path, "utf8"))));
  }

  return undefined;
}

function requiredFundedKeypair(): Keypair {
  const explicit =
    loadKeypair("SOLANA_DEPOSITOR_SECRET_KEY", "SOLANA_DEPOSITOR_KEYPAIR") ??
    loadKeypair("SOLANA_SECRET_KEY", "SOLANA_KEYPAIR");
  if (explicit !== undefined) {
    return explicit;
  }

  const defaultPath = `${process.env.HOME}/.config/solana/id.json`;
  if (fs.existsSync(defaultPath)) {
    return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(fs.readFileSync(defaultPath, "utf8"))));
  }

  throw new Error("Set SOLANA_DEPOSITOR_SECRET_KEY to the funded Solana keypair JSON array");
}

function keypairExport(name: string, keypair: Keypair): string {
  return `export ${name}='${JSON.stringify(Array.from(keypair.secretKey))}'`;
}

function pubkeyExport(name: string, pubkey: PublicKey): string {
  return `export ${name}=${pubkey.toBase58()}`;
}

function requiredPublicKey(name: string): PublicKey {
  const value = process.env[name];
  if (value === undefined || value.trim() === "") {
    throw new Error(
      `${name} is required and must be the committee-controlled encumbered public key`,
    );
  }
  return new PublicKey(value);
}

function hasValue(value: string | undefined): value is string {
  return value !== undefined && value.trim() !== "";
}

const rpcUrl = process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";
const connection = new Connection(rpcUrl, "finalized");
const depositor = requiredFundedKeypair();
const primary = hasValue(process.env.SOLANA_ENCUMBERED_ACCOUNT)
  ? requiredPublicKey("SOLANA_ENCUMBERED_ACCOUNT")
  : requiredPublicKey("SOLANA_PRIMARY_ACCOUNT");
const nonceAccount =
  loadKeypair("SOLANA_NONCE_SECRET_KEY", "SOLANA_NONCE_KEYPAIR") ?? Keypair.generate();
const outputPath =
  process.env.SOLANA_SETUP_OUTPUT_PATH ??
  "/home/ubuntu/.crossroads-solana-public-testnet.generated.env";

const nonceAccountInfo = await connection.getAccountInfo(nonceAccount.publicKey, "finalized");
const nonceRent = await connection.getMinimumBalanceForRentExemption(NONCE_ACCOUNT_LENGTH);

const tx = new Transaction();
const signers = [depositor];

if (nonceAccountInfo === null) {
  tx.add(
    ...SystemProgram.createNonceAccount({
      fromPubkey: depositor.publicKey,
      noncePubkey: nonceAccount.publicKey,
      authorizedPubkey: primary,
      lamports: nonceRent,
    }).instructions,
  );
  signers.push(nonceAccount);
}

let setupSignature: string | undefined;
if (tx.instructions.length > 0) {
  setupSignature = await sendAndConfirmTransaction(connection, tx, signers, {
    commitment: "finalized",
  });
}

const nonceInfo = await connection.getNonce(nonceAccount.publicKey, "finalized");
if (nonceInfo === null) {
  throw new Error(`Nonce account ${nonceAccount.publicKey.toBase58()} was not initialized`);
}
if (!nonceInfo.authorizedPubkey.equals(primary)) {
  throw new Error(
    `Nonce account ${nonceAccount.publicKey.toBase58()} authority ${nonceInfo.authorizedPubkey.toBase58()} does not match encumbered primary ${primary.toBase58()}`,
  );
}

const env = [
  "# Generated by scripts/setup-solana-public-testnet.ts",
  `export SOLANA_RPC_URL=${rpcUrl}`,
  keypairExport("SOLANA_NONCE_SECRET_KEY", nonceAccount),
  pubkeyExport("SOLANA_PRIMARY_ACCOUNT", primary),
  pubkeyExport("SOLANA_NONCE_ACCOUNT", nonceAccount.publicKey),
  pubkeyExport("SOLANA_ENCUMBERED_ACCOUNT", primary),
  "",
].join("\n");

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, env);
await fs.promises.chmod(outputPath, 0o600);

console.log(
  JSON.stringify(
    {
      rpcUrl,
      depositor: depositor.publicKey.toBase58(),
      encumberedPrimary: primary.toBase58(),
      nonceAccount: nonceAccount.publicKey.toBase58(),
      nonce: nonceInfo.nonce,
      setupSignature,
      outputPath,
    },
    null,
    2,
  ),
);
